Models/Entity/QuoteEntry.cs
namespace AspnetCoreMvcFull.Models { 

  public class QuoteEntry

  {

  public Guid? Id { get; set; }
  public string? NameFirst { get; set; }
  public string? NameLast { get; set; }
  public string? Mobile { get; set; }
  public string? Email { get; set; }
  public string? installationAddress { get; set; }
  public string? postAddress { get; set; }
  public string? companyName { get; set; }
  public string? ABNnumber { get; set; }
  public string? NMI { get; set; }
  public string? meterNumber { get; set; }
  public string? electricityRetailer { get; set; }
  public string? electricityDis { get; set; }
  public string? propertyPhase { get; set; }
  public string? preapprovalNumber { get; set; }
  public string? storyHouse { get; set; }
  public string? roofType { get; set; }
  public string? switchBoardUpgrade { get; set; }

  }


}

Models/Entity/QuotePDF.cs
namespace AspnetCoreMvcFull.Models { 

  public class QuotePDF

  {

  public Guid? Id { get; set; }
  public QuoteEntry? NameFirst { get; set; }
  public QuoteEntry? NameLast { get; set; }
  public QuoteEntry? Mobile { get; set; }
  public QuoteEntry? Email { get; set; }
  public QuoteEntry? installationAddress { get; set; }
  public QuoteEntry? postAddress { get; set; }
  public QuoteEntry? companyName { get; set; }
  public QuoteEntry? ABNnumber { get; set; }
  public QuoteEntry? NMI { get; set; }
  public QuoteEntry? meterNumber { get; set; }
  public QuoteEntry? electricityRetailer { get; set; }
  public QuoteEntry? electricityDis { get; set; }
  public QuoteEntry? propertyPhase { get; set; }
  public QuoteEntry? preapprovalNumber { get; set; }
  public QuoteEntry? storyHouse { get; set; }
  public QuoteEntry? roofType { get; set; }
  public QuoteEntry? switchBoardUpgrade { get; set; }

    public StockEntry? companyNamePanels { get; set; }
    public StockEntry? modelPanel { get; set; }
    public StockEntry? panelCapacity { get; set; }
    public StockEntry? numberPanels { get; set; }
    public StockEntry? pricePanel { get; set; }
    public StockEntry? imagePanel { get; set; }
    public StockEntry? companyNameInverter { get; set; }
    public StockEntry? modelInverter { get; set; }
    public StockEntry? inverterCapacity { get; set; }
    public StockEntry? inverterPhase { get; set; }
    public StockEntry? priceInverter { get; set; }
    public StockEntry? numberInverters { get; set; }
    public StockEntry? batteryNameInverter { get; set; }
    public StockEntry? batteryModel { get; set; }
    public StockEntry? batteryCapacity { get; set; }
    public StockEntry? batteryPhase { get; set; }
    public StockEntry? batteryPrice { get; set; }
    public StockEntry? numberBatteries { get; set; }
    public StockEntry? batteryImage { get; set; }

  }


}

Controllers/QuoteEntryController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Models;
using Solar1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Reflection;

namespace AspnetCoreMvcFull.Controllers;

public class QuoteEntryController : Controller
{
  private readonly ApplicationDbContext _context;

  public QuoteEntryController(ApplicationDbContext _context)
  {
    this._context = _context;
  }
   
  [HttpGet]
  public IActionResult Quote()
  {
    return View();
  }

  [HttpPost]
  public async Task<IActionResult> Quote(AddQuoteEntryViewModel viewModel)
  {
    var entity = new QuoteEntry
    {
      
      NameFirst = viewModel.NameFirst,
      NameLast = viewModel.NameLast,
      Mobile = viewModel.Mobile,
      installationAddress = viewModel.installationAddress,
      postAddress = viewModel.postAddress,
      Email = viewModel.Email,
      ABNnumber = viewModel.ABNnumber,
      companyName = viewModel.companyName,
      electricityDis = viewModel.electricityDis,
      electricityRetailer = viewModel.electricityRetailer,
      meterNumber = viewModel.meterNumber,
      NMI = viewModel.NMI,
      preapprovalNumber = viewModel.preapprovalNumber,
      propertyPhase = viewModel.propertyPhase,
      roofType = viewModel.roofType,
      storyHouse = viewModel.storyHouse,
      switchBoardUpgrade = viewModel.switchBoardUpgrade,

    };

    await _context.QuoteEntries.AddAsync(entity);
    await _context.SaveChangesAsync();

    return View();
  }

  [HttpGet]
  public async Task<IActionResult> QuotePDF(Guid id)
  {
    var QuoteEntity = await _context.QuoteEntries.FindAsync(id);

    return View(QuoteEntity);
  }

  [HttpGet]
  public async Task<IActionResult> Edit(Guid id)
  {
    var QuoteEntity = await _context.QuoteEntries.FindAsync(id);

    return View(QuoteEntity);
  }

  [HttpPost]
  public async Task<IActionResult> Edit(QuoteEntry viewModel)
  {
    var QuoteEntity = await _context.QuoteEntries.FindAsync(viewModel.Id);

    if (QuoteEntity is not null)
    {
      QuoteEntity.NameFirst = viewModel.NameFirst;
      QuoteEntity.NameLast = viewModel.NameLast;
      QuoteEntity.Mobile = viewModel.Mobile;
      QuoteEntity.installationAddress = viewModel.installationAddress;
      QuoteEntity.postAddress = viewModel.postAddress;
      QuoteEntity.Email = viewModel.Email;
      QuoteEntity.ABNnumber = viewModel.ABNnumber;
      QuoteEntity.companyName = viewModel.companyName;
      QuoteEntity.electricityDis = viewModel.electricityDis;
      QuoteEntity.electricityRetailer = viewModel.electricityRetailer;
      QuoteEntity.meterNumber = viewModel.meterNumber;
      QuoteEntity.NMI = viewModel.NMI;
      QuoteEntity.preapprovalNumber = viewModel.preapprovalNumber;
      QuoteEntity.propertyPhase = viewModel.propertyPhase;
      QuoteEntity.roofType = viewModel.roofType;
      QuoteEntity.storyHouse = viewModel.storyHouse;
      QuoteEntity.switchBoardUpgrade = viewModel.switchBoardUpgrade;

      await _context.SaveChangesAsync();

    }


    return RedirectToAction("SolarQuote", "SolarQuote");

  }


}

Views/QuoteEntry/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model AspnetCoreMvcFull.Models.QuoteEntry

<h1>Edit Client Details</h1>

@if (Model is null)
{

<p>No data available, there is no ID</p>

} else
{
	<form id="registrationForm" method="post">
		<div class="row mb-3">
			<div class="col-md-6">
				<label for="firstName" class="form-label">First Name</label>
				<input type="text" asp-for="NameFirst" class="form-control" id="firstName" placeholder="Enter first name" oninput="updatePreview()">
			</div>
			<div class="col-md-6">
				<label for="lastName" class="form-label">Last Name</label>
				<input type="text" asp-for="NameLast" class="form-control" id="lastName" placeholder="Enter last name" oninput="updatePreview()">
			</div>
		</div>
		<div class="row mb-3">
			<div class="col-md-6">
				<label for="mobile" class="form-label">Mobile</label>
				<input type="text" asp-for="Mobile" class="form-control" id="mobile" placeholder="Enter mobile number" oninput="updatePreview()">
			</div>
			<div class="col-md-6">
				<label for="email" class="form-label">Email</label>
				<input type="email" asp-for="Email" class="form-control" id="email" placeholder="Enter email address" oninput="updatePreview()">
			</div>
		</div>
		<div class="row mb-3">
			<div class="col-md-12">
				<label for="postAddress" class="form-label">Postal Address</label>
				<input type="text" asp-for="postAddress" class="form-control text-center" id="postAddress" placeholder="Enter postal address">
			</div>
			<div class="col-md-12">
				<label for="installationAddress" class="form-label">Installation Address</label>
				<input type="text" asp-for="installationAddress" class="form-control text-center" id="installationAddress" placeholder="Enter installation address" oninput="updatePreview()">
			</div>
		</div>
		<div class="row mb-3">
			<div class="col-md-6">
				<label for="companyName" class="form-label">Company Name</label>
				<input type="text" asp-for="companyName" class="form-control" id="companyName" placeholder="Enter company name" oninput="updatePreview()">
			</div>
			<div class="col-md-6">
				<label for="abnNum" class="form-label">ABN Number</label>
				<input type="text" asp-for="ABNnumber" class="form-control" id="abnNum" placeholder="Enter ABN number" oninput="updatePreview()">
			</div>
		</div>


		<!-- Electricity Bill Details Tab -->

		<h4>Electricity Bill Details</h4>

		<div class="row mb-3">
			<div class="col-md-6">
				<label for="meterNumber" class="form-label">Meter Number</label>
				<input type="text" asp-for="meterNumber" class="form-control" id="meterNumber" placeholder="Enter meter number" oninput="updatePreview()">
			</div>
			<div class="col-md-6">
				<label for="nmi" class="form-label">NMI</label>
				<input type="text" asp-for="NMI" class="form-control" id="nmi" placeholder="Enter NMI" oninput="updatePreview()">
			</div>
		</div>
		<div class="row mb-3">
			<div class="col-md-6">
				<label for="electricityDis" class="form-label">Electricity Distributor</label>
				<input type="text" asp-for="electricityDis" class="form-control" id="electricityDis" placeholder="Enter electricity distributor" oninput="updatePreview()">
			</div>
			<div class="col-md-6">
				<label for="electricityRetailer" class="form-label">Electricity Retailer</label>
				<input type="text" asp-for="electricityRetailer" class="form-control" id="electricityRetailer" placeholder="Enter electricity retailer" oninput="updatePreview()">
			</div>
		</div>
		<div class="row mb-3">
			<div class="col-md-6">
				<label for="propertyPhase" class="form-label">Property Phase</label>
				<input type="text" asp-for="propertyPhase" class="form-control" id="propertyPhase" placeholder="Enter property phase" oninput="updatePreview()">
			</div>
			<div class="col-md-6">
				<label for="preapprovalNumber" class="form-label">Preapproval Number</label>
				<input type="text" asp-for="preapprovalNumber" class="form-control" id="preapprovalNumber" placeholder="Enter preapproval number" oninput="updatePreview()">

			</div>
		</div>
		<div class="row mb-3">
		</div>




		<!-- House Details Tab -->

		<h4>House Details</h4>

		<div class="row mb-3">
			<div class="col-md-6">
				<label for="storyHouse" class="form-label">Story of House</label>
				<input type="text" asp-for="storyHouse" class="form-control" id="storyHouse" placeholder="Enter story of the house" oninput="updatePreview()">
			</div>
			<div class="col-md-6">
				<label for="roofType" class="form-label">Roof Type</label>
				<input type="text" asp-for="roofType" class="form-control" id="roofType" placeholder="Enter roof type" oninput="updatePreview()">
			</div>
		</div>

		<div class="row mb-3">
			<div class="col-md-6">
				<label for="switchBoardUpgrade" class="form-label">Switch Board Upgrade</label>
				<input type="text" asp-for="switchBoardUpgrade" class="form-control" id="switchBoardUpgrade" placeholder="Enter switch board upgrade status" oninput="updatePreview()">
			</div>
		</div>
		<button type="submit" id="submitButton" class="btn btn-primary">Submit</button>
	</form>
	
}

Views/QuoteEntry/QuotePDF.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model AspnetCoreMvcFull.Models.QuoteEntry

<h1>PDF Quote</h1>

@if (Model is null)
{

<p>No data available, there is no ID</p>

} else
{
	<section class="">

		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-6 vh-100 ">
					<form id="registrationForm" method="post">
						<h4>Personal Details</h4>
						<div class="row mb-3">
							<div class="col-md-6">
								<label for="firstName" class="form-label">First Name</label>
								<input type="text" asp-for="NameFirst" class="form-control" id="firstName" placeholder="Enter first name" oninput="updatePreview()">
							</div>
							<div class="col-md-6">
								<label for="lastName" class="form-label">Last Name</label>
								<input type="text" asp-for="NameLast" class="form-control" id="lastName" placeholder="Enter last name" oninput="updatePreview()">
							</div>
						</div>
						<div class="row mb-4">
							<div class="col-md-6">
								<label for="mobile" class="form-label">Mobile</label>
								<input type="text" asp-for="Mobile" class="form-control" id="mobile" placeholder="Enter mobile number" oninput="updatePreview()">
							</div>
							<div class="col-md-6">
								<label for="email" class="form-label">Email</label>
								<input type="email" asp-for="Email" class="form-control" id="email" placeholder="Enter email address" oninput="updatePreview()">
							</div>
						</div>
						<div class="row mb-3">
							<div class="col-md-12">
								<label for="postAddress" class="form-label">Postal Address</label>
								<input type="text" asp-for="postAddress" class="form-control text-center" id="postAddress" placeholder="Enter postal address">
							</div>
						</div>
						<div class="row mb-3">
							<div class="col-md-12">
								<label for="installationAddress" class="form-label">Installation Address</label>
								<input type="text" asp-for="installationAddress" class="form-control text-center" id="installationAddress" placeholder="Enter installation address" oninput="updatePreview()">
							</div>
						</div>
						<div class="row mb-3">
							<div class="col-md-6">
								<label for="companyName" class="form-label">Company Name</label>
								<input type="text" asp-for="companyName" class="form-control" id="companyName" placeholder="Enter company name" oninput="updatePreview()">
							</div>
							<div class="col-md-6">
								<label for="abnNum" class="form-label">ABN Number</label>
								<input type="text" asp-for="ABNnumber" class="form-control" id="abnNum" placeholder="Enter ABN number" oninput="updatePreview()">
							</div>
						</div>

						<h4>Electricity Bill Details</h4>

						<div class="row mb-3">
							<div class="col-md-6">
								<label for="meterNumber" class="form-label">Meter Number</label>
								<input type="text" asp-for="meterNumber" class="form-control" id="meterNumber" placeholder="Enter meter number" oninput="updatePreview()">
							</div>
							<div class="col-md-6">
								<label for="nmi" class="form-label">NMI</label>
								<input type="text" asp-for="NMI" class="form-control" id="nmi" placeholder="Enter NMI" oninput="updatePreview()">
							</div>
						</div>
						<div class="row mb-3">

							<div class="col-md-6">
								<label for="electricityDis" class="form-label">Electricity Distributor</label>
								<input type="text" asp-for="electricityDis" class="form-control" id="electricityDis" placeholder="Enter electricity distributor" oninput="updatePreview()">
							</div>

							<div class="col-md-6">
								<label for="electricityRetailer" class="form-label">Electricity Retailer</label>
								<input type="text" asp-for="electricityRetailer" class="form-control" id="electricityRetailer" placeholder="Enter electricity retailer" oninput="updatePreview()">
							</div>

						</div>
						<div class="row mb-4">

							<div class="col-md-2">
								<label for="propertyPhase" class="form-label">Property Phase</label>
								<input type="text" asp-for="propertyPhase" class="form-control" id="propertyPhase" placeholder="Enter property phase" oninput="updatePreview()">
							</div>
							
							<div class="col-md-6">
								<label for="preapprovalNumber" class="form-label">Preapproval Number</label>
								<input type="text" asp-for="preapprovalNumber" class="form-control" id="preapprovalNumber" placeholder="Enter preapproval number" oninput="updatePreview()">
							</div>
						</div>
						<br />
						
						<h4>Clients Bill</h4>

						<div class="row mb-3">

							<div class="col-md-6">
								<label for="meterNumber" class="form-label">Kwh</label>
								<input type="text" class="form-control" id="meterNumber" placeholder="Enter Kwh" oninput="updatePreview()">
							</div>

							<div class="col-md-6">
								<label for="nmi" class="form-label">Price</label>
								<input type="text" class="form-control" id="nmi" placeholder="Enter price" oninput="updatePreview()">
							</div>
						</div>
						
					</form>
				</div>
				<div class="col-lg-6 vh-100">

					<h4>House Details</h4>

					<div class="row mb-3">

						<div class="col-md-3">
							<label for="storyHouse" class="form-label">Story of House</label>
							<input type="text" asp-for="storyHouse" class="form-control" id="storyHouse" placeholder="Enter story of the house" oninput="updatePreview()">
						</div>

						<div class="col-md-3">
							<label for="roofType" class="form-label">Roof Type</label>
							<input type="text" asp-for="roofType" class="form-control" id="roofType" placeholder="Enter roof type" oninput="updatePreview()">
						</div>

						<div class="col-md-4">
							<label for="switchBoardUpgrade" class="form-label">Switch Board Upgrade</label>
							<input type="text" asp-for="switchBoardUpgrade" class="form-control" id="switchBoardUpgrade" placeholder="Enter switch board upgrade status" oninput="updatePreview()">
						</div>
					</div>

					<h4>Solar Panels</h4>

					<div class="row mb-3">

						<div class="col-md-6">
							<label for="firstName" class="form-label">Panel model:</label>
							<input type="text" asp-for="NameFirst" class="form-control" id="firstName" placeholder="Enter first name" oninput="updatePreview()">
						</div>

						<div class="col-md-6">
							<label for="lastName" class="form-label">Panel Number</label>
							<input type="text" asp-for="NameLast" class="form-control" id="lastName" placeholder="Enter last name" oninput="updatePreview()">
						</div>
				
					
						<div class="col-md-6">
							<label for="firstName" class="form-label">Panel Watt</label>
							<input type="text" asp-for="NameFirst" class="form-control" id="firstName" placeholder="Enter first name" oninput="updatePreview()">
						</div>

						<img class='col-md-3' src='https://www.austraenergy.com.au/wp-content/uploads/2024/02/Ai-LB-Pro-5K.fw_.png' alt=''>
					</div>


					<h4>Inverter System</h4>

					<!--Generated with a search or drop down-->
					<div class="row mb-3">
						<div class="col-md-6">
							<label for="firstName" class="form-label">Inverter model:</label>
							<input type="text" asp-for="NameFirst" class="form-control" id="firstName" placeholder="Enter first name" oninput="updatePreview()">
						</div>
						<div class="col-md-6">
							<label for="firstName" class="form-label">Inverter Number:</label>
							<input type="text" asp-for="NameFirst" class="form-control" id="firstName" placeholder="Enter first name" oninput="updatePreview()">
						</div>
						<div class="col-md-6">
							<label for="firstName" class="form-label">Inverter Size:</label>
							<input type="text" asp-for="NameFirst" class="form-control" id="firstName" placeholder="Enter first name" oninput="updatePreview()">
						</div>
						
						<img class='col-md-3' src='https://www.austraenergy.com.au/wp-content/uploads/2024/02/Ai-LB-Pro-5K.fw_.png' alt=''>
					</div>


					<div class="col-md-6">
					<h4>Mountings:</h4>
					
						<label for="firstName" class="form-label">Inverter Size:</label>
						<input type="text" asp-for="NameFirst" class="form-control" id="firstName" placeholder="Enter first name" oninput="updatePreview()">
					</div>
					
				</div>
			</div>
		</div>

		<br />
		<br />
		<br />
		<br />
		<br />
		<br />
		<br />
		<br />
		<br />
		<br />
		<br />
		<br />
	</section>
	<!--
		<a class="btn btn-primary" asp-controller="QuoteEntry" asp-action="QuotePDF" asp-route-id="">Update</a>
		<a class="btn btn-primary" asp-controller="QuoteEntry" asp-action="QuotePDF" asp-route-id="">Generate PDF</a>


	-->

}